#pragma once
#ifdef DEBUG
int DEBUG_OBJ_CONSTRUCTOR = 0;
int DEBUG_STRONG_REF_COUNT_CONSTRUCTOR = 0;
int DEBUG_WEAK_REF_COUNT_CONSTRUCTOR = 0;

int DEBUG_OBJ_DESTRUCTOR = 0;
int DEBUG_STRONG_REF_COUNT_DESTRUCTOR = 0;
int DEBUG_WEAK_REF_COUNT_DESTRUCTOR = 0;
#endif